### ISSUE TITLE
Need to clear data in Readme

### ISSUE THREAD

**Issue by jai-dewani** [shrutikapoor08/talent-for-hire#127]
A major reason why the web version still isn't uniform is due to a major problem with the inconsistency with the count of `|` which represents the columns of an entry. In a perfect world, there should be about 7 `|` in a row as clearly mentioned in this section -> [Looking for a job during COVID pandemic sucks!](https://github.com/shrutikapoor08/talent-for-hire#looking-for-a-job-during-covid-pandemic-sucks)

**Comment by shrutikapoor08** [comment]
DONE
