### ISSUE TITLE
Any Update on this Repository 

### ISSUE THREAD

**Issue by as8297** [shrutikapoor08/talent-for-hire#94]
I am glad that everyone is trying to help each other out in this tough time. I just want to know that, what happen after I fill my details here ? 

I want to know the status of people who has filled their details way before me. I doubt if its a legit helping place or just another data/star-collection scam. Please update.

Thank you.

**Comment by shrutikapoor08** [comment]
LOL
I am just trying to help people who are looking for a role and being the bridge between recruiters and potential employees.  I am sharing this list with my network of recruiters who reaches out regarding a job opening to me. Participation is completely voluntary of course. This is not a job board. 

You are welcome to help people too.
